CONTRACTION_MAP = {
"ain't": "is not",
"aren't": "are not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he would",
"he'd've": "he would have",
"he'll": "he will",
"he'll've": "he he will have",
"he's": "he is",
"how'd": "how did",
"how'd'y": "how do you",
"how'll": "how will",
"how's": "how is",
"I'd": "I would",
"I'd've": "I would have",
"I'll": "I will",
"I'll've": "I will have",
"I'm": "I am",
"I've": "I have",
"i'd": "i would",
"i'd've": "i would have",
"i'll": "i will",
"i'll've": "i will have",
"i'm": "i am",
"i've": "i have",
"isn't": "is not",
"it'd": "it would",
"it'd've": "it would have",
"it'll": "it will",
"it'll've": "it will have",
"it's": "it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"mightn't've": "might not have",
"must've": "must have",
"mustn't": "must not",
"mustn't've": "must not have",
"needn't": "need not",
"needn't've": "need not have",
"o'clock": "of the clock",
"oughtn't": "ought not",
"oughtn't've": "ought not have",
"shan't": "shall not",
"sha'n't": "shall not",
"shan't've": "shall not have",
"she'd": "she would",
"she'd've": "she would have",
"she'll": "she will",
"she'll've": "she will have",
"she's": "she is",
"should've": "should have",
"shouldn't": "should not",
"shouldn't've": "should not have",
"so've": "so have",
"so's": "so as",
"that'd": "that would",
"that'd've": "that would have",
"that's": "that is",
"there'd": "there would",
"there'd've": "there would have",
"there's": "there is",
"they'd": "they would",
"they'd've": "they would have",
"they'll": "they will",
"they'll've": "they will have",
"they're": "they are",
"they've": "they have",
"to've": "to have",
"wasn't": "was not",
"we'd": "we would",
"we'd've": "we would have",
"we'll": "we will",
"we'll've": "we will have",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what will",
"what'll've": "what will have",
"what're": "what are",
"what's": "what is",
"what've": "what have",
"when's": "when is",
"when've": "when have",
"where'd": "where did",
"where's": "where is",
"where've": "where have",
"who'll": "who will",
"who'll've": "who will have",
"who's": "who is",
"who've": "who have",
"why's": "why is",
"why've": "why have",
"will've": "will have",
"won't": "will not",
"won't've": "will not have",
"would've": "would have",
"wouldn't": "would not",
"wouldn't've": "would not have",
"y'all": "you all",
"y'all'd": "you all would",
"y'all'd've": "you all would have",
"y'all're": "you all are",
"y'all've": "you all have",
"you'd": "you would",
"you'd've": "you would have",
"you'll": "you will",
"you'll've": "you will have",
"you're": "you are",
"you've": "you have"
}

EXPAND_STOP_WORD = [
         'from', 'subject', 're', 'edu', 'use', 'not', 'would', 'say', 'could', '_', 'be', 'know', 'good', 'go', 'get',
         'do', 'done', 'try', 'many', 'some', 'nice', 'thank', 'think', 'see', 'rather', 'easy', 'easily', 'lot',
         'lack', 'make', 'want', 'seem', 'run', 'need', 'even', 'right', 'line', 'even', 'also', 'may', 'take', 'come',
         'im', 'theyre', "youre", 'wont', 'bc', 'hte', 'didnt', 'i', 'me', 'my', 'myself', 'we', 'our', 'ours',
         'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he',
         'youre', 'youve', 'youll', 'youd', 'dont', 'ive', 'theres', 'common', 'thing' 'things', 'way',
         'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they',
         'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these',
         'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does',
         'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at',
         'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above',
         'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then',
         'once', 'here', 'there', 'thered', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more',
         'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's',
         'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 't',
         'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn',
         "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn',
         "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't",
         'wouldn', "wouldn't", "there's", 'isnt', 'doesnt', 'arent', 'couldnt', 'doesnt', 'hadnt', 'hasnt'
         'havent', 'nightnt', 'mustnt', 'neednt', 'shant' 'shouldnt', 'wasnt', 'werent', 'wont', 'wouldnt'
]

TRHESHOLD_PARAMETER = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.99]

#
# LIST TOPIC

edukasi_5 = [['project', 'knowledge', 'time', 'problem', 'course'], ['project', 'background', 'work', 'problem', 'course'], ['background', 'content', 'class', 'lecture', 'course'], ['course', 'content', 'project', 'class', 'lecture'], ['content', 'time', 'course', 'class', 'background']]
edukasi_7 = [['project', 'knowledge', 'work', 'problem', 'course', 'information', 'book'], ['project', 'knowledge', 'work', 'problem', 'course', 'content', 'design'], ['study', 'project', 'work', 'course', 'knowledge', 'class', 'theory'], ['class', 'work', 'knowledge', 'design', 'course', 'content', 'project'], ['lecture', 'book', 'content', 'time', 'class', 'course', 'work']]

ecommerce_5 = [['shape', 'problem', 'dress', 'time', 'body'], ['length', 'problem', 'dress', 'time', 'body'], ['dress', 'quality', 'size', 'body', 'price'], ['dress', 'length', 'size', 'quality', 'body'], ['size', 'quality', 'woman', 'dress', 'clothes']]
ecommerce_7 = [['shape', 'problem', 'dress', 'time', 'body', 'store', 'baby'], ['shape','problem','dress', 'time', 'body', 'quality', 'baby'], ['dress', 'fabric', 'model', 'quality', 'price', 'body', 'top'], ['dress', 'model', 'length', 'quality', 'clothes', 'store', 'top'], ['quality', 'store', 'clothes', 'dress', 'model', 'size', 'woman']]

game_5 = [['problem', 'game', 'time', 'music', 'hit'], ['problem', 'game', 'time', 'content', 'player'], ['play', 'game', 'player', 'support', 'problem'], ['game', 'play', 'people', 'player', 'time'], ['problem', 'game', 'player', 'time', 'people']]
game_7 = [['problem', 'game', 'time', 'music', 'battle', 'support', 'people'], ['problem', 'game', 'setting', 'food', 'player', 'support', 'people'], ['time', 'setting', 'people', 'play', 'game', 'player', 'problem'], ['support', 'time', 'setting', 'play', 'player', 'game', 'problem'], ['people', 'problem', 'player', 'play', 'game', 'battle', 'time']]

manual_edukasi_5 = [['process', 'knowledge', 'education', 'problem', 'course']]
manual_ecommerce_5 = [['shape', 'problem', 'style', 'time', 'body']]
manual_game_5 = [['problem', 'people', 'time', 'fight', 'spot']]

edukasi_5_1000 = [['project', 'knowledge', 'problem', 'course', 'education'], ['project', 'knowledge', 'people', 'course', 'education'], ['basic', 'project', 'knowledge', 'course', 'class'], ['teacher', 'course', 'knowledge', 'process', 'basic'], ['time', 'knowledge', 'project', 'design', 'course']]
edukasi_7_1000 = [['project', 'knowledge', 'problem', 'class', 'basic', 'people', 'course'], ['project', 'knowledge', 'education', 'class', 'process', 'people', 'course'], ['project', 'people', 'basic', 'student', 'knowledge', 'process', 'teacher'], ['class', 'class', 'basic', 'people', 'process', 'course', 'basic'], ['lecture', 'basic', 'process', 'project', 'process', 'course', 'knowledge']]
ecommerce_5_1000 = [['body', 'person', 'time', 'dress', 'shop'], ['body', 'person', 'time', 'dress', 'shop'], ['dress', 'body', 'material', 'dress', 'shop'], ['review', 'shop', 'design', 'dress', 'store'], ['store', 'size', 'shop', 'shop', 'dress']]
ecommerce_7_1000 = [['shape', 'problem', 'time', 'dress', 'shop', 'body', 'woman'], ['shape', 'problem', 'time', 'dress', 'shop', 'body', 'baby'], ['shape', 'body', 'body', 'dress', 'size', 'store', 'time'], ['shape', 'size', 'store', 'dress', 'quality', 'style', 'shirt'], ['dress', 'size', 'material', 'quality', 'size', 'fabric', 'store']]
game_5_1000 = [['problem', 'play', 'time', 'battle', 'place'], ['problem', 'play', 'setting', 'player', 'menu'], ['game', 'play', 'support', 'problem', 'performance'], ['player', 'player', 'setting', 'way', 'problem'], ['problem', 'player', 'people', 'game', 'people']]
game_7_1000 = [['problem', 'play', 'time', 'body', 'work', 'connection', 'support'], ['problem', 'play', 'time', 'player', 'menu', 'connection', 'support'], ['problem', 'performance', 'menu', 'connection', 'play', 'people', 'game'], ['game', 'problem', 'support', 'connection', 'people', 'setting', 'content'], ['game', 'player', 'connection', 'problem', 'time', 'tool', 'place']]

edukasi_5_1500 = [['project', 'knowledge', 'course', 'people', 'process'], ['project', 'knowledge', 'course', 'people', 'process'], ['knowledge', 'web', 'class', 'game', 'basic'], ['basic', 'class', 'way', 'knowledge', 'course'], ['class', 'project', 'basic', 'work', 'teacher']]
edukasi_7_1500 = [['project', 'knowledge', 'course', 'problem', 'process', 'basic', 'people'], ['project', 'knowledge', 'course', 'problem', 'process', 'basic', 'people'], ['web', 'knowledge', 'process', 'practice', 'basic', 'project', 'lecture'], ['learning', 'design', 'project', 'course', 'process', 'course', 'education'], ['lecture', 'course', 'knowledge', 'people', 'development', 'video', 'project']]
ecommerce_5_1500 = [['quality', 'body', 'person', 'baby', 'time'], ['dress', 'body', 'style', 'shop', 'time'], ['dress', 'shop', 'style', 'quality', 'store'], ['person', 'size', 'dress', 'quality', 'shop'], ['dress', 'quality', 'size', 'store', 'dress']]
ecommerce_7_1500 = [['quality', 'body', 'person', 'time', 'time', 'baby', 'dress'], ['quality', 'body', 'person', 'shop', 'time', 'top', 'dress'], ['top', 'fabric', 'shape', 'quality', 'dress', 'size', 'style'], ['size', 'quality', 'shape', 'dress', 'clothes', 'shop', 'person'], ['fabric', 'dress', 'quality', 'size', 'body', 'store', 'style']]
game_5_1500 = [['problem', 'play', 'setting', 'battle', 'future'], ['problem', 'play', 'setting', 'player', 'menu'], ['setting', 'menu', 'people', 'problem', 'player'], ['setting', 'player', 'play', 'people', 'problem'], ['player', 'time', 'people', 'problem', 'game']]
game_7_1500 = [['problem', 'play', 'time', 'place', 'food', 'connection', 'future'], ['problem', 'play', 'time', 'player', 'content', 'connection', 'ability'], ['game', 'connection', 'problem', 'problem', 'player', 'setting', 'review'], ['problem', 'support', 'review', 'connection', 'play', 'people', 'player'], ['game', 'problem', 'play', 'player', 'people', 'connection', 'fight']]

lti_edukasi_5 = [['process', 'knowledge', 'education', 'people', 'exam'], ['group', 'knowledge', 'work', 'people', 'teacher'], ['knowledge', 'knowledge', 'action', 'activity', 'task'], ['mind', 'theme', 'group', 'group', 'language'], ['information', 'group', 'exam', 'work', 'education']]
lti_edukasi_7 = [['job', 'knowledge', 'game', 'people', 'exam', 'process', 'background'], ['knowledge', 'knowledge', 'game', 'people', 'teacher', 'communication', 'knowledge'], ['group', 'career', 'group', 'group', 'mind', 'teacher', 'care'], ['knowledge', 'group', 'teacher', 'expert', 'education', 'group', 'group'], ['job', 'work', 'information', 'teacher', 'action', 'knowledge', 'work']]

lti_ecommerce_5 = [['side', 'someone', 'way', 'period', 'chest'], ['structure', 'someone', 'shop', 'quality', 'cord'], ['paint', 'way', 'quality', 'chest', 'expert'], ['coat', 'style', 'fashion', 'print', 'shoulder'], ['paint', 'quality', 'cloth', 'style', 'quality']]
lti_ecommerce_7 = [['side', 'someone', 'style', 'period', 'chest', 'shop', 'babe'], ['bag', 'someone', 'coat', 'winter', 'cord', 'shop', 'babe'], ['suit', 'shop', 'quality', 'style', 'length', 'chest', 'top'], ['canvas', 'someone', 'cloth', 'quality', 'cardigan', 'fashion', 'way'], ['fashion', 'shop', 'suit', 'coat', 'style', 'quality', 'shop']]

lti_game_5 = [['someone', 'people', 'day', 'future', 'spot'], ['connection', 'people', 'yesterday', 'group', 'device'], ['yesterday', 'connection', 'battle', 'case', 'age'], ['picture', 'battle', 'power', 'buddy', 'world'], ['case', 'power', 'case', 'case', 'case']]
lti_game_7 = [['someone', 'way', 'tomorrow', 'action', 'spot', 'event', 'quality'], ['connection', 'way', 'yesterday', 'food', 'device', 'love', 'day'], ['case', 'battle', 'group', 'part', 'connection', 'drama', 'battle'], ['knowledge', 'yesterday', 'battle', 'group', 'part', 'activity', 'convert'], ['activity', 'case', 'activity', 'battle', 'group', 'battle', 'case']]

lti_edukasi_5_1000 = [['knowledge', 'knowledge', 'people', 'event', 'communication'], ['knowledge', 'knowledge', 'people', 'education', 'activity'], ['project', 'work', 'knowledge', 'teacher', 'group'], ['group', 'activity', 'mind', 'knowledge', 'project'], ['work', 'work', 'work', 'action', 'activity']]
lti_edukasi_7_1000 = [['job', 'knowledge', 'someone', 'game', 'communication', 'people', 'work'], ['knowledge', 'knowledge', 'paper', 'game', 'procedure', 'people', 'teacher'], ['group', 'group', 'work', 'use', 'language', 'event', 'group'], ['professional', 'education', 'group', 'period', 'specialist', 'group', 'knowledge'], ['work', 'action', 'education', 'work', 'work', 'teacher', 'group']]
lti_ecommerce_5_1000 = [['person', 'someone', 'period', 'way', 'shop'], ['chest', 'person', 'day', 'denim', 'shop'], ['way', 'chest', 'fall', 'style', 'shop'], ['style', 'clothes', 'case', 'quality', 'shop'], ['fashion', 'canvas', 'fashion', 'shop', 'clothes']]
lti_ecommerce_7_1000 = [['side', 'someone', 'period', 'way', 'shop', 'head', 'someone'], ['pound', 'someone', 'period', 'coat', 'shop', 'body', 'babe'], ['quality', 'piece', 'denim', 'pink', 'length', 'shop', 'autumn'], ['paper', 'body', 'shop', 'spring', 'quality', 'quality', 'location'], ['fashion', 'length', 'paint', 'style', 'cloth', 'canvas', 'style']]
lti_game_5_1000 = [['situation', 'people', 'day', 'fight', 'spot'], ['person', 'people', 'yesterday', 'device', 'group'], ['power', 'group', 'battle', 'group', 'group'], ['event', 'group', 'power', 'way', 'location'], ['case', 'person', 'group', 'battle', 'case']]
lti_game_7_1000 = [['situation', 'people', 'minute', 'ground', 'worth', 'part', 'event'], ['situation', 'people', 'minute', 'part', 'group', 'device', 'delay'], ['way', 'machine', 'group', 'project', 'power', 'part', 'scene'], ['game', 'battle', 'activity', 'power', 'group', 'device', 'group'], ['power', 'case', 'case', 'case', 'way', 'case', 'way']]

lti_edukasi_5_1500 = [['knowledge', 'knowledge', 'event', 'people', 'process'], ['knowledge', 'knowledge', 'education', 'group', 'procedure'], ['action', 'degree', 'group', 'example', 'work'], ['knowledge', 'event', 'group', 'knowledge', 'activity'], ['work', 'education', 'action', 'work', 'teacher']]
lti_edukasi_7_1500 = [['work', 'knowledge', 'help', 'someone', 'process', 'code', 'people'], ['knowledge', 'knowledge', 'education', 'paper', 'activity', 'assessment', 'people'], ['event', 'teacher', 'activity', 'assessment', 'knowledge', 'group', 'event'], ['group', 'theme', 'work', 'program', 'activity', 'education', 'knowledge'], ['event', 'education', 'action', 'work', 'action', 'work', 'work']]
lti_ecommerce_5_1500 = [['quality', 'head', 'someone', 'period', 'day'], ['cloth', 'shoulder', 'way', 'shop', 'day'], ['age', 'case', 'style', 'quality', 'shop'], ['someone', 'denim', 'fashion', 'quality', 'shop'], ['denim', 'fashion', 'cloth', 'shop', 'style']]
lti_ecommerce_7_1500 = [['quality', 'head', 'thought', 'period', 'period', 'woman', 'coat'], ['quality', 'neck', 'someone', 'shop', 'day', 'art', 'denim'], ['person', 'adult', 'part', 'cover', 'style', 'piece', 'quality'], ['age', 'quality', 'fashion', 'middle', 'yesterday', 'piece', 'denim'], ['canvas', 'denim', 'fashion', 'canvas', 'style', 'fashion', 'shop']]
lti_game_5_1500 = [['situation', 'people', 'day', 'fight', 'space'], ['person', 'people', 'tomorrow', 'device', 'group'], ['group', 'story', 'power', 'group', 'style'], ['fault', 'group', 'part', 'people', 'way'],['person', 'case', 'group', 'buddy', 'case']]
lti_game_7_1500 = [['situation', 'people', 'day', 'spot', 'group', 'part', 'idea'], ['person', 'people', 'day', 'room', 'package', 'device', 'quality'], ['group', 'project', 'case', 'group', 'power', 'girlfriend', 'knowledge'], ['battle', 'group', 'activity', 'battle', 'power', 'group', 'case'], ['way', 'case', 'case', 'buddy', 'case', 'activity', 'battle']]

manual_edukasi_7 = [['project', 'knowledge', 'work', 'people', 'course', 'process', 'background']]

#   LIST LDA SORT LDA 500/1000/1500

lda_edukasi_5 = [{1: ['course', 'time', 'concept', 'video', 'knowledge', 'professor', 'work', 'idea', 'problem', 'exercise'], 2: ['theory', 'content', 'material', 'way', 'character', 'specialization', 'job', 'topic', 'background', 'people'], 3: ['assignment', 'project', 'tool', 'example', 'data', 'student', 'galaxy', 'resume', 'experience', 'level'], 4: ['design', 'week', 'information', 'introduction', 'class', 'question', 'teacher', 'forum', 'discussion', 'review'], 5: ['game', 'lecture', 'thing', 'explanation', 'instructor', 'basic', 'skill', 'designer', 'feedback', 'kind']}, {1: ['unity', 'instructor', 'thanks', 'experience', 'quiz', 'teacher', 'galaxy', 'explanation', 'fun', 'lesson'], 2: ['course', 'introduction', 'project', 'concept', 'information', 'theory', 'way', 'problem', 'instruction', 'resume'], 3: ['lecture', 'thing', 'video', 'knowledge', 'level', 'intro', 'designer', 'background', 'principle', 'point'], 4: ['design', 'time', 'material', 'content', 'example', 'specialization', 'process', 'data', 'job', 'character'], 5: ['game', 'assignment', 'development', 'week', 'idea', 'class', 'basic', 'work', 'student', 'tool']}, {1: ['thing', 'thanks', 'content', 'information', 'class', 'theory', 'basic', 'idea', 'work', 'specialization'], 2: ['game', 'assignment', 'unity', 'time', 'week', 'video', 'instructor', 'experience', 'quiz', 'web'], 3: ['development', 'design', 'material', 'way', 'example', 'topic', 'beginner', 'tool', 'cs', 'people'], 4: ['introduction', 'project', 'knowledge', 'teacher', 'student', 'javascript', 'level', 'document', 'bit', 'designer'], 5: ['course', 'lecture', 'concept', 'coursera', 'problem', 'lesson', 'galaxy', 'forum', 'practice', 'kind']}]
lda_edukasi_7 = [{1: ['example', 'class', 'specialization', 'problem', 'level', 'question', 'peer', 'application', 'answer', 'lot'], 2: ['assignment', 'concept', 'video', 'way', 'galaxy', 'work', 'explanation', 'people', 'teacher', 'balance'], 3: ['introduction', 'material', 'knowledge', 'professor', 'idea', 'instructor', 'thanks', 'artist', 'review', 'fun'], 4: ['design', 'theory', 'student', 'experience', 'background', 'process', 'field', 'basic', 'designer', 'tip'], 5: ['course', 'time', 'week', 'thing', 'topic', 'quiz', 'exercise', 'principle', 'coursera', 'discussion'], 6: ['lecture', 'content', 'sheet', 'exam', 'approach', 'quality', 'case', 'document', 'resource', 'hope'], 7: ['game', 'project', 'information', 'tool', 'data', 'character', 'resume', 'job', 'forum', 'skill']}, {1: ['instructor', 'example', 'student', 'beginner', 'topic', 'teacher', 'character', 'skill', 'insight', 'documentation'], 2: ['game', 'class', 'experience', 'specialization', 'knowledge', 'work', 'quiz', 'point', 'practice', 'opinion'], 3: ['design', 'project', 'way', 'galaxy', 'review', 'background', 'principle', 'forum', 'tutorial', 'bit'], 4: ['assignment', 'week', 'theory', 'tool', 'people', 'question', 'resume', 'end', 'lesson', 'kind'], 5: ['unity', 'professor', 'problem', 'job', 'document', 'coursera', 'designer', 'exercise', 'answer', 'field'], 6: ['course', 'development', 'lecture', 'video', 'information', 'material', 'content', 'process', 'data', 'level'], 7: ['time', 'introduction', 'concept', 'thing', 'idea', 'thanks', 'basic', 'step', 'hand', 'peer']}, {1: ['thanks', 'instructor', 'content', 'class', 'basic', 'hand', 'yaakov', 'aspect', 'learning', 'chaikin'], 2: ['design', 'video', 'material', 'information', 'topic', 'cs', 'step', 'problem', 'review', 'designer'], 3: ['assignment', 'introduction', 'time', 'project', 'thing', 'way', 'theory', 'work', 'quiz', 'web'], 4: ['game', 'lecture', 'concept', 'experience', 'example', 'beginner', 'idea', 'student', 'professor', 'coursera'], 5: ['unity', 'specialization', 'process', 'intro', 'peer', 'tutorial', 'character', 'bit', 'forum', 'engine'], 6: ['course', 'development', 'html', 'developer', 'practice', 'quality', 'opportunity', 'approach', 'script', 'start'], 7: ['week', 'knowledge', 'teacher', 'tool', 'javascript', 'fun', 'people', 'job', 'instruction', 'document']}]

lda_ecommerce_5 = [{1: ['dress', 'fabric', 'material', 'jacket', 'look', 'design', 'sweater', 'love', 'cut', 'shoulder'], 2: ['shirt', 'length', 'way', 'medium', 'pant', 'time', 'online', 'pattern', 'body', 'winter'], 3: ['size', 'color', 'fit', 'quality', 'waist', 'style', 'retailer', 'blouse', 'model', 'work'], 4: ['skirt', 'x', 'summer', 'bit', 'print', 'sale', 'weight', 'shape', 'feel', 'picture'], 5: ['store', 'jean', 'sleeve', 'petite', 'chest', 'lb', 'order', 'spring', 'knee', 'neck']}, {1: ['fabric', 'sweater', 'way', 'sleeve', 'bit', 'person', 'review', 'hip', 'day', 'feel'], 2: ['shirt', 'jean', 'look', 'love', 'sale', 'price', 'blouse', 'work', 'cute', 'photo'], 3: ['skirt', 'length', 'retailer', 'jacket', 'design', 'time', 'fall', 'online', 'pattern', 'reviewer'], 4: ['size', 'dress', 'fit', 'pant', 'quality', 'style', 'medium', 'model', 'arm', 'picture'], 5: ['color', 'material', 'store', 'waist', 'coat', 'x', 'petite', 'shoulder', 'cut', 'compliment']}, {1: ['color', 'fabric', 'skirt', 'summer', 'person', 'time', 'body', 'picture', 'piece', 'pattern'], 2: ['size', 'jean', 'waist', 'model', 'jacket', 'love', 'x', 'day', 'coat', 'work'], 3: ['dress', 'fit', 'sweater', 'material', 'length', 'pant', 'style', 'medium', 'look', 'sleeve'], 4: ['shirt', 'quality', 'retailer', 'arm', 'design', 'petite', 'bit', 'shoulder', 'reviewer', 'cute'], 5: ['way', 'store', 'sale', 'review', 'thing', 'legging', 'tee', 'bust', 'suit', 'item']}]
lda_ecommerce_7 = [{1: ['size', 'dress', 'fabric', 'work', 'hip', 'petite', 'piece', 'lb', 'denim', 'inch'], 2: ['waist', 'design', 'jean', 'model', 'shoulder', 'summer', 'person', 'top', 'weight', 'compliment'], 3: ['fit', 'length', 'jacket', 'medium', 'reviewer', 'lace', 'body', 'arm', 'button', 'fall'], 4: ['quality', 'cut', 'shape', 'picture', 'bust', 'order', 'photo', 'neck', 'tee', 'year'], 5: ['color', 'material', 'sweater', 'sleeve', 'blouse', 'x', 'print', 'coat', 'knit', 'half'], 6: ['shirt', 'skirt', 'way', 'retailer', 'pant', 'love', 'bit', 'online', 'day', 'pattern'], 7: ['style', 'store', 'look', 'time', 'sale', 'review', 'chest', 'hem', 'thing', 'dot']}, {1: ['material', 'arm', 'pattern', 'cute', 'picture', 'year', 'suit', 'inch', 'torso', 'pocket'], 2: ['size', 'skirt', 'jacket', 'sale', 'feel', 'body', 'neckline', 'area', 'thing', 'spring'], 3: ['color', 'fit', 'length', 'store', 'retailer', 'sleeve', 'love', 'x', 'review', 'compliment'], 4: ['dress', 'jean', 'model', 'look', 'bit', 'person', 'petite', 'fall', 'online', 'summer'], 5: ['sweater', 'pant', 'quality', 'day', 'work', 'knee', 'kind', 'wool', 'lining', 'light'], 6: ['fabric', 'way', 'waist', 'style', 'medium', 'coat', 'time', 'cut', 'price', 'blouse'], 7: ['shirt', 'design', 'shoulder', 'hip', 'photo', 'piece', 'weight', 'print', 'hem', 'room']}, {1: ['size', 'length', 'way', 'store', 'arm', 'love', 'summer', 'cut', 'picture', 'feel'], 2: ['quality', 'style', 'price', 'time', 'bit', 'fall', 'hip', 'pattern', 'compliment', 'legging'], 3: ['color', 'material', 'look', 'sleeve', 'x', 'petite', 'blouse', 'review', 'body', 'shape'], 4: ['dress', 'skirt', 'model', 'cute', 'thing', 'area', 'button', 'figure', 'stretch', 'strap'], 5: ['fit', 'shirt', 'jacket', 'day', 'online', 'print', 'chest', 'lace', 'lb', 'year'], 6: ['sweater', 'pant', 'waist', 'retailer', 'medium', 'sale', 'shoulder', 'coat', 'piece', 'reviewer'], 7: ['fabric', 'jean', 'design', 'person', 'order', 'weight', 'neck', 'neckline', 'knee', 'torso']}]

lda_game_5 = [{1: ['game', 'connection', 'graphic', 'experience', 'console', 'story', 'release', 'mhw', 'online', 'character'], 2: ['version', 'keyboard', 'support', 'fps', 'mw', 'option', 'mission', 'performance', 'play', 'fight'], 3: ['hour', 'people', 'review', 'way', 'mouse', 'control', 'server', 'series', 'gameplay', 'hunt'], 4: ['issue', 'friend', 'multiplayer', 'player', 'port', 'problem', 'thing', 'combat', 'capcom', 'controller'], 5: ['monster', 'time', 'hunter', 'pc', 'weapon', 'world', 'p', 'bug', 'day', 'launch']}, {1: ['monster', 'hour', 'review', 'fps', 'hunt', 'support', 'mission', 'feel', 'solo', 'armor'], 2: ['game', 'friend', 'multiplayer', 'weapon', 'player', 'people', 'server', 'gameplay', 'combat', 'story'], 3: ['time', 'world', 'thing', 'connection', 'fun', 'series', 'control', 'mw', 'version', 'graphic'], 4: ['way', 'experience', 'keyboard', 'day', 'steam', 'content', 'point', 'session', 'fix', 'reason'], 5: ['issue', 'hunter', 'pc', 'port', 'problem', 'mouse', 'controller', 'mh', 'console', 'play']}, {1: ['port', 'controller', 'graphic', 'capcom', 'version', 'fps', 'mh', 'day', 'armor', 'error'], 2: ['monster', 'time', 'issue', 'hour', 'weapon', 'multiplayer', 'player', 'world', 'connection', 'fun'], 3: ['combat', 'p', 'play', 'keyboard', 'feel', 'mission', 'patch', 'item', 'launch', 'minute'], 4: ['game', 'hunter', 'people', 'series', 'experience', 'content', 'fix', 'money', 'fan', 'work'], 5: ['pc', 'friend', 'review', 'thing', 'problem', 'way', 'gameplay', 'story', 'console', 'support']}]
lda_game_7 = [{1: ['issue', 'hour', 'support', 'story', 'release', 'armor', 'money', 'quest', 'attack', 'enemy'], 2: ['time', 'hunter', 'mouse', 'month', 'day', 'option', 'mhw', 'minute', 'character', 'bit'], 3: ['review', 'port', 'combat', 'server', 'experience', 'version', 'series', 'setting', 'steam', 'mission'], 4: ['pc', 'friend', 'multiplayer', 'people', 'way', 'controller', 'fun', 'keyboard', 'p', 'year'], 5: ['player', 'world', 'problem', 'control', 'connection', 'graphic', 'gameplay', 'mw', 'session', 'content'], 6: ['game', 'monster', 'weapon', 'console', 'item', 'kind', 'crash', 'disconnect', 'cpu', 'type'], 7: ['thing', 'capcom', 'hunt', 'fps', 'bug', 'fix', 'mh', 'fan', 'online', 'person']}, {1: ['mouse', 'fun', 'gameplay', 'mw', 'performance', 'session', 'fix', 'mhw', 'attack', 'enemy'], 2: ['issue', 'pc', 'combat', 'hunt', 'steam', 'bug', 'fight', 'month', 'disconnect', 'kind'], 3: ['game', 'world', 'support', 'point', 'option', 'area', 'armor', 'type', 'design', 'gtx'], 4: ['time', 'hour', 'multiplayer', 'review', 'connection', 'server', 'story', 'series', 'control', 'version'], 5: ['friend', 'people', 'port', 'experience', 'mh', 'console', 'end', 'online', 'character', 'solo'], 6: ['monster', 'hunter', 'weapon', 'player', 'problem', 'controller', 'graphic', 'fps', 'keyboard', 'setting'], 7: ['thing', 'way', 'capcom', 'content', 'cutscenes', 'year', 'reason', 'feel', 'money', 'launch']}, {1: ['issue', 'problem', 'capcom', 'console', 'fight', 'point', 'mission', 'fix', 'year', 'fan'], 2: ['thing', 'fun', 'series', 'support', 'content', 'feel', 'release', 'soul', 'connectivity', 'design'], 3: ['monster', 'hunter', 'weapon', 'review', 'controller', 'mw', 'armor', 'end', 'work', 'reason'], 4: ['way', 'combat', 'option', 'session', 'online', 'error', 'bit', 'change', 'map', 'gb'], 5: ['game', 'friend', 'hour', 'gameplay', 'hunt', 'control', 'setting', 'p', 'play', 'quest'], 6: ['pc', 'people', 'server', 'story', 'version', 'fps', 'bug', 'patch', 'area', 'month'], 7: ['time', 'multiplayer', 'player', 'port', 'world', 'connection', 'mouse', 'graphic', 'experience', 'mh']}]

#   LIST LDA SORT LDA-TFIDF 500/1000/1500

ldat_edukasi_5 = [{1: ['design', 'time', 'concept', 'material', 'data', 'character', 'idea', 'background', 'thanks', 'principle'], 2: ['content', 'video', 'example', 'class', 'specialization', 'explanation', 'experience', 'people', 'artist', 'basic'], 3: ['theory', 'week', 'introduction', 'thing', 'job', 'exercise', 'discussion', 'review', 'analysis', 'business'], 4: ['game', 'lecture', 'tool', 'student', 'galaxy', 'resume', 'instructor', 'topic', 'process', 'quiz'], 5: ['assignment', 'project', 'information', 'way', 'knowledge', 'professor', 'work', 'problem', 'level', 'question']}, {1: ['assignment', 'introduction', 'unity', 'thanks', 'basic', 'work', 'process', 'topic', 'peer', 'lesson'], 2: ['game', 'project', 'week', 'material', 'content', 'beginner', 'problem', 'fun', 'intro', 'resume'], 3: ['design', 'development', 'lecture', 'theory', 'example', 'experience', 'knowledge', 'character', 'document', 'designer'], 4: ['time', 'video', 'instructor', 'way', 'idea', 'specialization', 'student', 'quiz', 'professor', 'step'], 5: ['concept', 'thing', 'information', 'class', 'tool', 'people', 'question', 'teacher', 'data', 'explanation']}, {1: ['video', 'knowledge', 'work', 'specialization', 'cs', 'step', 'question', 'hand', 'intro', 'character'], 2: ['lecture', 'way', 'tool', 'web', 'professor', 'coursera', 'level', 'instruction', 'document', 'point'], 3: ['introduction', 'time', 'project', 'thanks', 'instructor', 'content', 'class', 'basic', 'topic', 'idea'], 4: ['game', 'development', 'unity', 'week', 'thing', 'material', 'information', 'experience', 'example', 'theory'], 5: ['design', 'assignment', 'concept', 'teacher', 'beginner', 'process', 'quiz', 'explanation', 'job', 'html']}]
ldat_edukasi_7 = [{1: ['time', 'galaxy', 'exercise', 'teacher', 'coursera', 'review', 'step', 'study', 'prototype', 'addition'], 2: ['introduction', 'professor', 'specialization', 'resume', 'job', 'artist', 'balance', 'business', 'tip', 'answer'], 3: ['design', 'tool', 'class', 'student', 'character', 'thing', 'topic', 'field', 'designer', 'development'], 4: ['game', 'lecture', 'content', 'material', 'example', 'data', 'way', 'problem', 'background', 'people'], 5: ['theory', 'project', 'week', 'video', 'knowledge', 'experience', 'principle', 'discussion', 'end', 'skill'], 6: ['assignment', 'information', 'concept', 'idea', 'explanation', 'instructor', 'level', 'quiz', 'thanks', 'forum'], 7: ['work', 'question', 'process', 'basic', 'analysis', 'option', 'algebra', 'day', 'rest', 'thought']}, {1: ['development', 'project', 'way', 'content', 'tool', 'question', 'professor', 'level', 'character', 'peer'], 2: ['thing', 'idea', 'work', 'people', 'topic', 'galaxy', 'job', 'intro', 'review', 'coursera'], 3: ['game', 'assignment', 'time', 'introduction', 'unity', 'lecture', 'information', 'basic', 'beginner', 'problem'], 4: ['week', 'student', 'explanation', 'kind', 'engine', 'practice', 'prototype', 'understanding', 'application', 'dev'], 5: ['video', 'thanks', 'class', 'specialization', 'knowledge', 'quiz', 'step', 'document', 'resume', 'designer'], 6: ['concept', 'instructor', 'theory', 'material', 'experience', 'process', 'exercise', 'forum', 'learning', 'winn'], 7: ['design', 'example', 'teacher', 'data', 'hand', 'feedback', 'approach', 'grading', 'option', 'day']}, {1: ['thing', 'thanks', 'video', 'way', 'concept', 'web', 'step', 'job', 'intro', 'lesson'], 2: ['game', 'design', 'instructor', 'material', 'knowledge', 'teacher', 'example', 'theory', 'hand', 'problem'], 3: ['introduction', 'specialization', 'process', 'end', 'document', 'stuff', 'resume', 'background', 'issue', 'lecturer'], 4: ['week', 'javascript', 'quiz', 'coursera', 'question', 'review', 'exercise', 'bit', 'learning', 'practice'], 5: ['assignment', 'content', 'information', 'basic', 'beginner', 'idea', 'explanation', 'level', 'point', 'field'], 6: ['project', 'class', 'experience', 'topic', 'tool', 'work', 'student', 'fun', 'cs', 'people'], 7: ['development', 'unity', 'time', 'lecture', 'professor', 'instruction', 'galaxy', 'star', 'winn', 'start']}]

ldat_ecommerce_5 = [{1: ['dress', 'color', 'material', 'retailer', 'sleeve', 'love', 'petite', 'pattern', 'lace', 'feel'], 2: ['shirt', 'quality', 'style', 'jacket', 'medium', 'sweater', 'model', 'online', 'compliment', 'arm'], 3: ['size', 'fit', 'skirt', 'length', 'look', 'time', 'summer', 'work', 'print', 'body'], 4: ['fabric', 'waist', 'store', 'way', 'blouse', 'pant', 'cut', 'shoulder', 'bit', 'hip'], 5: ['design', 'jean', 'person', 'reviewer', 'sale', 'weight', 'shape', 'bust', 'chest', 'price']}, {1: ['size', 'dress', 'style', 'time', 'person', 'hip', 'online', 'work', 'cute', 'lace'], 2: ['pant', 'medium', 'petite', 'shoulder', 'fall', 'price', 'blouse', 'feel', 'picture', 'neck'], 3: ['material', 'jacket', 'pattern', 'summer', 'bust', 'chest', 'year', 'spring', 'knit', 'leg'], 4: ['fit', 'sweater', 'shirt', 'length', 'quality', 'way', 'sleeve', 'model', 'coat', 'design'], 5: ['color', 'fabric', 'skirt', 'store', 'jean', 'waist', 'retailer', 'look', 'love', 'bit']}, {1: ['dress', 'color', 'fit', 'sweater', 'pant', 'model', 'summer', 'person', 'petite', 'price'], 2: ['fabric', 'length', 'sleeve', 'design', 'sale', 'time', 'online', 'pattern', 'weight', 'bra'], 3: ['size', 'skirt', 'way', 'style', 'jacket', 'blouse', 'body', 'picture', 'fall', 'shape'], 4: ['quality', 'waist', 'retailer', 'medium', 'look', 'arm', 'review', 'cut', 'shoulder', 'coat'], 5: ['shirt', 'material', 'store', 'jean', 'love', 'day', 'bit', 'reviewer', 'top', 'bust']}]
ldat_ecommerce_7 = [{1: ['shirt', 'sweater', 'online', 'piece', 'sale', 'chest', 'year', 'area', 'bra', 'dot'], 2: ['color', 'fabric', 'store', 'jacket', 'blouse', 'bit', 'work', 'hip', 'print', 'shape'], 3: ['dress', 'fit', 'look', 'model', 'love', 'reviewer', 'body', 'picture', 'arm', 'order'], 4: ['quality', 'way', 'design', 'cut', 'shoulder', 'summer', 'petite', 'compliment', 'button', 'winter'], 5: ['skirt', 'length', 'waist', 'style', 'retailer', 'medium', 'day', 'weight', 'review', 'lb'], 6: ['size', 'pant', 'time', 'person', 'pattern', 'lace', 'feel', 'knee', 'neck', 'torso'], 7: ['material', 'jean', 'sleeve', 'top', 'hem', 'photo', 'inch', 'purchase', 'comfy', 'navy']}, {1: ['model', 'look', 'price', 'pattern', 'work', 'summer', 'lace', 'shape', 'legging', 'suit'], 2: ['shirt', 'pant', 'retailer', 'coat', 'bit', 'feel', 'piece', 'body', 'tee', 'thing'], 3: ['fit', 'material', 'length', 'jean', 'waist', 'love', 'arm', 'sale', 'review', 'shoulder'], 4: ['dress', 'color', 'cut', 'online', 'cute', 'picture', 'compliment', 'blue', 'button', 'torso'], 5: ['size', 'quality', 'sleeve', 'petite', 'weight', 'neckline', 'top', 'area', 'year', 'stretch'], 6: ['sweater', 'skirt', 'store', 'way', 'style', 'jacket', 'design', 'order', 'lb', 'neck'], 7: ['fabric', 'medium', 'time', 'person', 'fall', 'hip', 'day', 'print', 'knee', 'denim']}, {1: ['shirt', 'waist', 'retailer', 'person', 'bit', 'order', 'chest', 'bra', 'blue', 'winter'], 2: ['fabric', 'love', 'petite', 'price', 'pair', 'suit', 'fun', 'tank', 'comfy', 'woman'], 3: ['medium', 'sale', 'shoulder', 'cute', 'shape', 'compliment', 'lace', 'button', 'hem', 'item'], 4: ['sweater', 'material', 'length', 'skirt', 'sleeve', 'time', 'cut', 'body', 'picture', 'fall'], 5: ['dress', 'way', 'pant', 'look', 'design', 'jacket', 'summer', 'review', 'hip', 'online'], 6: ['size', 'color', 'fit', 'store', 'jean', 'coat', 'piece', 'reviewer', 'pattern', 'feel'], 7: ['quality', 'style', 'model', 'arm', 'blouse', 'day', 'work', 'print', 'lb', 'thing']}]

ldat_game_5 = [{1: ['issue', 'hunter', 'hour', 'world', 'controller', 'fun', 'gameplay', 'hunt', 'fps', 'day'], 2: ['monster', 'pc', 'multiplayer', 'capcom', 'server', 'connection', 'console', 'month', 'performance', 'crash'], 3: ['player', 'port', 'thing', 'graphic', 'version', 'mw', 'content', 'week', 'armor', 'fight'], 4: ['time', 'friend', 'people', 'review', 'weapon', 'combat', 'mouse', 'control', 'experience', 'support'], 5: ['problem', 'way', 'series', 'keyboard', 'story', 'setting', 'session', 'fix', 'patch', 'connectivity']}, {1: ['multiplayer', 'world', 'problem', 'way', 'fun', 'controller', 'control', 'hunt', 'fight', 'year'], 2: ['time', 'hunter', 'pc', 'review', 'player', 'people', 'gameplay', 'story', 'series', 'play'], 3: ['monster', 'friend', 'connection', 'combat', 'version', 'setting', 'support', 'session', 'mechanic', 'release'], 4: ['issue', 'weapon', 'port', 'mouse', 'graphic', 'capcom', 'console', 'day', 'content', 'point'], 5: ['hour', 'thing', 'server', 'mw', 'experience', 'fps', 'keyboard', 'mh', 'mission', 'performance']}, {1: ['monster', 'time', 'player', 'port', 'controller', 'graphic', 'setting', 'play', 'day', 'content'], 2: ['world', 'story', 'experience', 'version', 'quest', 'option', 'performance', 'mission', 'release', 'error'], 3: ['issue', 'multiplayer', 'review', 'people', 'connection', 'hunt', 'control', 'mh', 'patch', 'armor'], 4: ['hunter', 'pc', 'thing', 'problem', 'series', 'capcom', 'mw', 'console', 'support', 'steam'], 5: ['friend', 'hour', 'weapon', 'fun', 'server', 'way', 'gameplay', 'combat', 'mouse', 'fps']}]
ldat_game_7 = [{1: ['time', 'way', 'capcom', 'series', 'gameplay', 'keyboard', 'support', 'story', 'patch', 'money'], 2: ['monster', 'issue', 'hour', 'combat', 'graphic', 'hunt', 'setting', 'steam', 'year', 'content'], 3: ['people', 'weapon', 'thing', 'controller', 'mw', 'option', 'crash', 'error', 'enemy', 'menu'], 4: ['hunter', 'friend', 'multiplayer', 'port', 'mouse', 'control', 'month', 'release', 'session', 'item'], 5: ['pc', 'review', 'connection', 'experience', 'fps', 'bug', 'day', 'mh', 'kind', 'work'], 6: ['player', 'play', 'week', 'cutscenes', 'title', 'type', 'person', 'solo', 'yes', 'fact'], 7: ['world', 'problem', 'server', 'version', 'fun', 'console', 'fix', 'launch', 'fight', 'disconnect']}, {1: ['monster', 'issue', 'port', 'way', 'story', 'day', 'quest', 'fix', 'patch', 'mhw'], 2: ['hunter', 'pc', 'multiplayer', 'weapon', 'experience', 'performance', 'release', 'feel', 'error', 'fan'], 3: ['friend', 'connection', 'combat', 'controller', 'capcom', 'keyboard', 'option', 'reason', 'menu', 'fact'], 4: ['hour', 'review', 'mouse', 'series', 'mh', 'console', 'support', 'cutscenes', 'work', 'disconnect'], 5: ['world', 'thing', 'control', 'mw', 'graphic', 'play', 'content', 'mission', 'fight', 'mechanic'], 6: ['time', 'player', 'people', 'problem', 'server', 'version', 'point', 'item', 'money', 'week'], 7: ['fun', 'gameplay', 'fps', 'hunt', 'setting', 'steam', 'bug', 'session', 'area', 'minute']}, {1: ['monster', 'pc', 'people', 'graphic', 'support', 'content', 'mission', 'release', 'area', 'money'], 2: ['gameplay', 'option', 'end', 'month', 'work', 'solo', 'disconnect', 'crash', 'change', 'dragon'], 3: ['time', 'issue', 'hour', 'fun', 'mouse', 'capcom', 'version', 'mw', 'steam', 'online'], 4: ['multiplayer', 'problem', 'server', 'series', 'experience', 'hunt', 'fps', 'mh', 'console', 'play'], 5: ['hunter', 'way', 'story', 'combat', 'control', 'day', 'point', 'error', 'mechanic', 'character'], 6: ['friend', 'player', 'world', 'connection', 'controller', 'setting', 'bug', 'performance', 'fix', 'cutscenes'], 7: ['weapon', 'review', 'thing', 'port', 'feel', 'year', 'kind', 'map', 'cpu', 'fact']}]


# LIST BTM 500/1000/1500

btm_edukasi_5 = [{1: ['course', 'assignment', 'video', 'question', 'time', 'lecture', 'quiz', 'info', 'instructor', 'content'], 2: ['course', 'design', 'forum', 'time', 'lecture', 'week', 'learning', 'people', 'video', 'experience'], 3: ['course', 'game', 'theory', 'week', 'example', 'problem', 'quiz', 'introduction', 'math', 'time'], 4: ['course', 'design', 'game', 'example', 'time', 'thing', 'assignment', 'process', 'information', 'level'], 5: ['course', 'information', 'concept', 'data', 'kind', 'lecture', 'end', 'tool', 'introduction', 'job']}, {1: ['course', 'game', 'assignment', 'video', 'idea', 'introduction', 'example', 'question', 'time', 'week'], 2: ['course', 'game', 'design', 'concept', 'development', 'assignment', 'week', 'knowledge', 'video', 'information'], 3: ['course', 'game', 'development', 'unity', 'experience', 'introduction', 'design', 'time', 'project', 'assignment'], 4: ['course', 'game', 'theory', 'time', 'design', 'lecture', 'week', 'development', 'aspect', 'kind'], 5: ['course', 'concept', 'time', 'lecture', 'tool', 'week', 'assignment', 'specialization', 'information', 'quiz']}, {1: ['course', 'game', 'design', 'instructor', 'concept', 'assignment', 'way', 'knowledge', 'video', 'thing'], 2: ['course', 'game', 'development', 'introduction', 'unity', 'time', 'knowledge', 'project', 'teacher', 'specialization'], 3: ['course', 'game', 'design', 'basic', 'unity', 'introduction', 'theory', 'cs', 'experience', 'development'], 4: ['course', 'time', 'concept', 'game', 'tool', 'assignment', 'example', 'project', 'work', 'week'], 5: ['course', 'assignment', 'time', 'video', 'content', 'way', 'lecture', 'question', 'material', 'instructor']}]
btm_edukasi_7 = [{1: ['course', 'kind', 'job', 'design', 'end', 'lecture', 'forum', 'discussion', 'review', 'year'], 2: ['course', 'time', 'design', 'assignment', 'tool', 'example', 'peer', 'week', 'page', 'word'], 3: ['course', 'question', 'assignment', 'info', 'video', 'time', 'example', 'option', 'prototype', 'file'], 4: ['course', 'information', 'time', 'week', 'quiz', 'concept', 'thing', 'lecture', 'instructor', 'example'], 5: ['course', 'data', 'introduction', 'concept', 'information', 'lecture', 'game', 'theory', 'tool', 'end'], 6: ['course', 'game', 'theory', 'skill', 'introduction', 'content', 'design', 'application', 'regard', 'math'], 7: ['course', 'design', 'game', 'theory', 'class', 'process', 'idea', 'assignment', 'designer', 'work']}, {1: ['course', 'assignment', 'video', 'time', 'lecture', 'professor', 'question', 'work', 'tool', 'example'], 2: ['course', 'game', 'basic', 'week', 'unity', 'introduction', 'instructor', 'theory', 'time', 'experience'], 3: ['course', 'game', 'concept', 'development', 'introduction', 'information', 'lecture', 'specialization', 'knowledge', 'design'], 4: ['course', 'time', 'peer', 'week', 'project', 'design', 'idea', 'tool', 'point', 'example'], 5: ['course', 'game', 'development', 'design', 'assignment', 'unity', 'idea', 'process', 'thing', 'concept'], 6: ['course', 'time', 'quiz', 'week', 'concept', 'lecture', 'information', 'example', 'thing', 'instructor'], 7: ['course', 'game', 'design', 'video', 'knowledge', 'information', 'project', 'class', 'instructor', 'content']}, {1: ['course', 'game', 'design', 'unity', 'experience', 'week', 'lecture', 'end', 'time', 'code'], 2: ['course', 'time', 'instructor', 'material', 'topic', 'assignment', 'experience', 'quiz', 'professor', 'coursera'], 3: ['course', 'game', 'cs', 'development', 'javascript', 'web', 'introduction', 'tool', 'html', 'knowledge'], 4: ['course', 'game', 'design', 'information', 'video', 'assignment', 'knowledge', 'people', 'instructor', 'thing'], 5: ['course', 'game', 'development', 'unity', 'introduction', 'design', 'idea', 'theory', 'video', 'thing'], 6: ['course', 'assignment', 'video', 'question', 'time', 'content', 'lecture', 'idea', 'example', 'review'], 7: ['course', 'time', 'example', 'concept', 'work', 'week', 'tool', 'project', 'knowledge', 'assignment']}]

btm_ecommerce_5 = [{1: ['size', 'color', 'fit', 'shirt', 'love', 'sleeve', 'dress', 'length', 'material', 'fabric'], 2: ['dress', 'size', 'fabric', 'color', 'length', 'waist', 'fit', 'quality', 'material', 'design'], 3: ['color', 'size', 'fabric', 'fit', 'top', 'pant', 'person', 'bra', 'blouse', 'retailer'], 4: ['color', 'size', 'way', 'fit', 'quality', 'model', 'style', 'jean', 'skirt', 'dress'], 5: ['color', 'size', 'fabric', 'dress', 'fit', 'model', 'shirt', 'bit', 'quality', 'medium']}, {1: ['dress', 'fit', 'size', 'color', 'fabric', 'jean', 'skirt', 'store', 'petite', 'style'], 2: ['size', 'fit', 'dress', 'waist', 'length', 'fabric', 'color', 'sleeve', 'arm', 'medium'], 3: ['size', 'fabric', 'color', 'quality', 'retailer', 'dress', 'fit', 'style', 'feel', 'online'], 4: ['color', 'size', 'dress', 'fabric', 'fit', 'sleeve', 'sweater', 'store', 'skirt', 'pant'], 5: ['color', 'size', 'sweater', 'jean', 'fall', 'medium', 'day', 'dress', 'fit', 'coat']}, {1: ['color', 'size', 'fit', 'fabric', 'dress', 'sleeve', 'jean', 'sweater', 'waist', 'look'], 2: ['size', 'fit', 'retailer', 'fabric', 'material', 'way', 'shirt', 'length', 'quality', 'color'], 3: ['dress', 'size', 'fabric', 'length', 'medium', 'color', 'fit', 'quality', 'sweater', 'waist'], 4: ['size', 'color', 'dress', 'store', 'fit', 'medium', 'way', 'material', 'shirt', 'quality'], 5: ['color', 'dress', 'size', 'fabric', 'length', 'skirt', 'way', 'pant', 'summer', 'jean']}]
btm_ecommerce_7 = [{1: ['size', 'shirt', 'color', 'fit', 'style', 'fabric', 'material', 'quality', 'summer', 'shape'], 2: ['color', 'size', 'dress', 'fabric', 'store', 'quality', 'look', 'fit', 'sleeve', 'way'], 3: ['size', 'dress', 'fit', 'color', 'material', 'medium', 'waist', 'shirt', 'work', 'sweater'], 4: ['fit', 'size', 'fabric', 'shirt', 'person', 'bit', 'neck', 'blouse', 'jacket', 'pant'], 5: ['time', 'color', 'size', 'dress', 'design', 'tag', 'hem', 'weight', 'retailer', 'style'], 6: ['fabric', 'dress', 'size', 'fit', 'quality', 'retailer', 'color', 'length', 'waist', 'model'], 7: ['color', 'size', 'style', 'skirt', 'store', 'sleeve', 'person', 'fabric', 'waist', 'pant']}, {1: ['dress', 'fabric', 'size', 'retailer', 'fit', 'petite', 'quality', 'store', 'color', 'way'], 2: ['size', 'color', 'jean', 'fit', 'waist', 'length', 'skirt', 'pant', 'look', 'petite'], 3: ['size', 'color', 'sweater', 'fit', 'sleeve', 'fall', 'dress', 'material', 'winter', 'photo'], 4: ['size', 'color', 'dress', 'sweater', 'fit', 'quality', 'way', 'shape', 'material', 'waist'], 5: ['color', 'size', 'fabric', 'fit', 'sleeve', 'waist', 'cut', 'style', 'jacket', 'material'], 6: ['color', 'dress', 'fabric', 'material', 'time', 'model', 'sweater', 'skirt', 'retailer', 'fit'], 7: ['size', 'color', 'fit', 'person', 'store', 'way', 'quality', 'dress', 'sale', 'pant']}, {1: ['size', 'dress', 'color', 'fabric', 'fit', 'material', 'length', 'shirt', 'retailer', 'medium'], 2: ['size', 'fabric', 'color', 'fit', 'sweater', 'sleeve', 'jean', 'length', 'dress', 'material'], 3: ['size', 'dress', 'fabric', 'length', 'fit', 'waist', 'retailer', 'quality', 'way', 'color'], 4: ['color', 'dress', 'size', 'fabric', 'material', 'fit', 'length', 'sweater', 'price', 'medium'], 5: ['color', 'size', 'fit', 'way', 'dress', 'waist', 'shirt', 'body', 'blouse', 'shoulder'], 6: ['color', 'size', 'store', 'dress', 'pant', 'skirt', 'petite', 'quality', 'sale', 'style'], 7: ['color', 'retailer', 'fabric', 'dress', 'store', 'fit', 'time', 'love', 'style', 'look']}]

btm_game_5 = [{1: ['game', 'issue', 'review', 'hour', 'problem', 'time', 'pc', 'gameplay', 'way', 'graphic'], 2: ['game', 'monster', 'time', 'weapon', 'hunter', 'combat', 'control', 'thing', 'pc', 'way'], 3: ['game', 'hunter', 'monster', 'time', 'world', 'issue', 'pc', 'multiplayer', 'version', 'weapon'], 4: ['game', 'monster', 'friend', 'hunter', 'time', 'world', 'issue', 'multiplayer', 'story', 'year'], 5: ['game', 'monster', 'issue', 'hunter', 'time', 'pc', 'people', 'hour', 'friend', 'mouse']}, {1: ['game', 'pc', 'monster', 'issue', 'friend', 'hunter', 'time', 'mouse', 'port', 'people'], 2: ['game', 'monster', 'time', 'hunter', 'player', 'thing', 'world', 'pc', 'weapon', 'way'], 3: ['game', 'monster', 'friend', 'time', 'hunter', 'multiplayer', 'people', 'story', 'issue', 'world'], 4: ['monster', 'game', 'weapon', 'time', 'combat', 'hunter', 'gameplay', 'issue', 'thing', 'hour'], 5: ['game', 'issue', 'time', 'hour', 'monster', 'thing', 'multiplayer', 'hunter', 'friend', 'problem']}, {1: ['game', 'time', 'hour', 'issue', 'monster', 'way', 'review', 'friend', 'hunter', 'player'], 2: ['game', 'monster', 'hunter', 'time', 'issue', 'pc', 'weapon', 'gameplay', 'review', 'thing'], 3: ['game', 'monster', 'pc', 'friend', 'hour', 'issue', 'player', 'people', 'time', 'graphic'], 4: ['game', 'monster', 'friend', 'hunter', 'time', 'player', 'weapon', 'multiplayer', 'issue', 'hour'], 5: ['game', 'monster', 'time', 'hunter', 'thing', 'pc', 'port', 'fun', 'hour', 'way']}]
btm_game_7 = [{1: ['game', 'hunter', 'monster', 'issue', 'pc', 'multiplayer', 'friend', 'experience', 'world', 'review'], 2: ['game', 'monster', 'weapon', 'player', 'issue', 'people', 'pc', 'review', 'time', 'series'], 3: ['game', 'time', 'monster', 'friend', 'multiplayer', 'story', 'player', 'year', 'aspect', 'area'], 4: ['game', 'hunter', 'weapon', 'monster', 'issue', 'combat', 'gameplay', 'time', 'way', 'thing'], 5: ['game', 'time', 'way', 'hour', 'issue', 'capcom', 'player', 'multiplayer', 'steam', 'people'], 6: ['game', 'combat', 'monster', 'time', 'attack', 'weapon', 'hunter', 'world', 'way', 'control'], 7: ['game', 'pc', 'issue', 'port', 'time', 'hour', 'friend', 'mouse', 'people', 'monster']}, {1: ['game', 'monster', 'hunter', 'time', 'pc', 'way', 'thing', 'friend', 'weapon', 'control'], 2: ['game', 'monster', 'friend', 'issue', 'time', 'multiplayer', 'hunter', 'player', 'fact', 'review'], 3: ['game', 'issue', 'time', 'pc', 'mouse', 'story', 'connection', 'friend', 'monster', 'problem'], 4: ['game', 'pc', 'monster', 'hunter', 'time', 'port', 'gameplay', 'people', 'issue', 'friend'], 5: ['game', 'time', 'steam', 'hour', 'monster', 'way', 'review', 'mission', 'friend', 'multiplayer'], 6: ['game', 'monster', 'issue', 'hunter', 'hour', 'thing', 'controller', 'mouse', 'pc', 'time'], 7: ['game', 'monster', 'weapon', 'hunter', 'time', 'world', 'way', 'thing', 'point', 'item']}, {1: ['game', 'monster', 'time', 'hunter', 'weapon', 'thing', 'world', 'feature', 'way', 'hour'], 2: ['game', 'time', 'pc', 'hour', 'monster', 'hunter', 'thing', 'port', 'mhw', 'issue'], 3: ['game', 'monster', 'time', 'weapon', 'pc', 'hour', 'gameplay', 'hunter', 'fun', 'thing'], 4: ['game', 'monster', 'friend', 'issue', 'hunter', 'time', 'multiplayer', 'hour', 'player', 'world'], 5: ['game', 'monster', 'time', 'hunter', 'issue', 'people', 'player', 'thing', 'friend', 'pc'], 6: ['game', 'pc', 'issue', 'friend', 'monster', 'port', 'console', 'review', 'connection', 'mouse'], 7: ['game', 'monster', 'weapon', 'player', 'fight', 'time', 'thing', 'armor', 'combat', 'hunter']}]


#   LIST LDA-GLOVE 0,7 500/1000/1500

ldag7_edukasi_5 = [{1: ['project', 'information', 'experience', 'level', 'process', 'development', 'learning', 'addition', 'career', 'resource'], 2: ['example', 'character', 'knowledge', 'explanation', 'approach', 'opinion', 'quality', 'understanding', 'reference', 'effort'], 3: ['time', 'week', 'class', 'work', 'job', 'field', 'step', 'business', 'fun', 'practice'], 4: ['way', 'thing', 'idea', 'problem', 'people', 'end', 'kind', 'answer', 'world', 'lot'], 5: ['course', 'lecture', 'student', 'question', 'thanks', 'teacher', 'presentation', 'exam', 'math', 'study']}, {1: ['project', 'experience', 'level', 'learning', 'resource', 'career', 'opportunity', 'view', 'science', 'challenge'], 2: ['example', 'knowledge', 'character', 'explanation', 'approach', 'opinion', 'understanding', 'effort', 'quality', 'reference'], 3: ['thing', 'way', 'idea', 'people', 'question', 'problem', 'lot', 'end', 'answer', 'kind'], 4: ['course', 'time', 'week', 'thanks', 'class', 'work', 'teacher', 'step', 'job', 'fun'], 5: ['development', 'introduction', 'information', 'tool', 'process', 'document', 'resume', 'exercise', 'discussion', 'option']}, {1: ['project', 'experience', 'level', 'learning', 'opportunity', 'career', 'focus', 'resource', 'science', 'challenge'], 2: ['knowledge', 'example', 'explanation', 'character', 'understanding', 'quality', 'approach', 'effort', 'opinion', 'reference'], 3: ['course', 'time', 'week', 'thanks', 'teacher', 'class', 'work', 'fun', 'step', 'job'], 4: ['thing', 'way', 'idea', 'people', 'question', 'problem', 'end', 'lot', 'point', 'stuff'], 5: ['development', 'introduction', 'information', 'tool', 'process', 'document', 'exercise', 'resume', 'issue', 'discussion']}]
ldag7_edukasi_7 = [{1: ['project', 'experience', 'level', 'learning', 'addition', 'career', 'resource', 'opportunity', 'building', 'challenge'], 2: ['example', 'knowledge', 'explanation', 'approach', 'opinion', 'quality', 'understanding', 'effort', 'statement', 'majority'], 3: ['time', 'week', 'class', 'work', 'job', 'field', 'step', 'business', 'fun', 'practice'], 4: ['way', 'thing', 'idea', 'problem', 'people', 'end', 'kind', 'answer', 'world', 'lot'], 5: ['course', 'lecture', 'student', 'question', 'thanks', 'teacher', 'presentation', 'exam', 'math', 'study'], 6: ['information', 'tool', 'resume', 'process', 'exercise', 'discussion', 'analysis', 'development', 'application', 'issue'], 7: ['theory', 'introduction', 'character', 'background', 'review', 'book', 'document', 'reference', 'experiment', 'description']}, {1: ['project', 'experience', 'level', 'learning', 'resource', 'career', 'opportunity', 'challenge', 'community', 'focus'], 2: ['example', 'knowledge', 'character', 'explanation', 'approach', 'opinion', 'understanding', 'effort', 'quality', 'reference'], 3: ['thing', 'idea', 'problem', 'answer', 'kind', 'stuff', 'fact', 'piece', 'thought', 'person'], 4: ['week', 'class', 'work', 'job', 'fun', 'lesson', 'practice', 'start', 'day', 'help'], 5: ['development', 'introduction', 'information', 'tool', 'process', 'document', 'resume', 'exercise', 'discussion', 'option'], 6: ['game', 'time', 'way', 'people', 'step', 'lot', 'end', 'point', 'field', 'bit'], 7: ['course', 'lecture', 'thanks', 'student', 'question', 'teacher', 'study', 'book', 'test', 'presentation']}, {1: ['project', 'experience', 'level', 'learning', 'opportunity', 'career', 'focus', 'resource', 'challenge', 'building'], 2: ['knowledge', 'example', 'explanation', 'understanding', 'quality', 'approach', 'effort', 'opinion', 'language', 'excellent'], 3: ['course', 'week', 'thanks', 'teacher', 'class', 'work', 'fun', 'job', 'lesson', 'practice'], 4: ['thing', 'idea', 'question', 'problem', 'stuff', 'kind', 'answer', 'fact', 'person', 'thought'], 5: ['development', 'information', 'tool', 'process', 'exercise', 'resume', 'issue', 'discussion', 'application', 'analysis'], 6: ['introduction', 'theory', 'review', 'document', 'character', 'background', 'code', 'script', 'book', 'programming'], 7: ['game', 'time', 'way', 'people', 'step', 'end', 'lot', 'point', 'field', 'bit']}]
ldag7_ecommerce_5 = [{1: ['shape', 'room', 'woman', 'edge', 'flat', 'side', 'sky', 'swing', 'hide', 'middle'], 2: ['person', 'piece', 'thing', 'problem', 'figure', 'opinion', 'type', 'fact', 'kind', 'reason'], 3: ['dress', 'fit', 'shirt', 'style', 'look', 'top', 'picture', 'cute', 'wear', 'baby'], 4: ['way', 'time', 'love', 'summer', 'bit', 'work', 'day', 'feel', 'fall', 'year'], 5: ['cut', 'shoulder', 'body', 'chest', 'arm', 'knee', 'neck', 'hole', 'hand', 'tank']}, {1: ['arm', 'shape', 'body', 'neck', 'chest', 'room', 'hole', 'woman', 'light', 'side'], 2: ['person', 'piece', 'thing', 'problem', 'reference', 'figure', 'kind', 'reason', 'type', 'fact'], 3: ['way', 'love', 'time', 'bit', 'fall', 'day', 'work', 'feel', 'summer', 'year'], 4: ['dress', 'fit', 'shirt', 'style', 'look', 'cut', 'cute', 'picture', 'top', 'blue'], 5: ['quality', 'store', 'order', 'fun', 'clothes', 'plenty', 'buy', 'christmas', 'holiday', 'bag']}, {1: ['fit', 'quality', 'medium', 'price', 'piece', 'shape', 'pocket', 'brand', 'product', 'green'], 2: ['arm', 'body', 'chest', 'blue', 'neck', 'hole', 'woman', 'side', 'hand', 'light'], 3: ['person', 'picture', 'cute', 'thing', 'problem', 'figure', 'kind', 'reference', 'type', 'perfect'], 4: ['cut', 'top', 'spring', 'bust', 'room', 'month', 'season', 'wash', 'baby', 'half'], 5: ['way', 'look', 'love', 'summer', 'time', 'day', 'bit', 'fall', 'work', 'feel']}]
ldag7_ecommerce_7 = [{1: ['shape', 'room', 'woman', 'edge', 'flat', 'side', 'sky', 'swing', 'hide', 'middle'], 2: ['person', 'piece', 'thing', 'problem', 'figure', 'opinion', 'type', 'fact', 'kind', 'reason'], 3: ['dress', 'fit', 'shirt', 'style', 'look', 'top', 'picture', 'cute', 'wear', 'outfit'], 4: ['way', 'time', 'summer', 'bit', 'work', 'day', 'feel', 'fall', 'year', 'half'], 5: ['cut', 'shoulder', 'body', 'chest', 'arm', 'knee', 'neck', 'hole', 'hand', 'tank'], 6: ['quality', 'store', 'order', 'fun', 'buy', 'christmas', 'clothes', 'holiday', 'list', 'stuff'], 7: ['love', 'baby', 'girl', 'green', 'boo', 'mom', 'party', 'saw', 'drop', 'smell']}, {1: ['shape', 'room', 'woman', 'side', 'edge', 'bottom', 'flat', 'line', 'inside', 'middle'], 2: ['person', 'piece', 'thing', 'problem', 'reference', 'figure', 'kind', 'reason', 'type', 'fact'], 3: ['way', 'time', 'bit', 'fall', 'day', 'work', 'feel', 'summer', 'year', 'today'], 4: ['dress', 'fit', 'shirt', 'style', 'look', 'cute', 'picture', 'top', 'wear', 'short'], 5: ['quality', 'store', 'order', 'fun', 'clothes', 'plenty', 'buy', 'christmas', 'holiday', 'bag'], 6: ['arm', 'shoulder', 'cut', 'body', 'neck', 'blue', 'chest', 'knee', 'hole', 'tank'], 7: ['love', 'girl', 'baby', 'saw', 'one', 'green', 'hood', 'party', 'mom', 'throw']}, {1: ['fit', 'quality', 'price', 'shape', 'brand', 'product', 'flat', 'plenty', 'business', 'beauty'], 2: ['arm', 'body', 'chest', 'neck', 'hole', 'woman', 'side', 'hand', 'edge', 'touch'], 3: ['person', 'thing', 'problem', 'figure', 'kind', 'reference', 'type', 'perfect', 'thought', 'fact'], 4: ['cut', 'bust', 'room', 'month', 'season', 'wash', 'half', 'night', 'week', 'office'], 5: ['way', 'love', 'summer', 'time', 'day', 'bit', 'fall', 'work', 'feel', 'year'], 6: ['look', 'picture', 'cute', 'top', 'wear', 'short', 'baby', 'girl', 'outfit', 'clothes'], 7: ['dress', 'shirt', 'style', 'medium', 'jacket', 'coat', 'piece', 'blue', 'spring', 'pair']}]
ldag7_game_5 = [{1: ['friend', 'problem', 'thing', 'story', 'kind', 'minute', 'reason', 'character', 'type', 'person'], 2: ['game', 'time', 'people', 'world', 'way', 'support', 'fix', 'year', 'play', 'point'], 3: ['hour', 'experience', 'fun', 'setting', 'month', 'day', 'session', 'week', 'money', 'work'], 4: ['food', 'worth', 'breaking', 'heart', 'music', 'plenty', 'build', 'everybody', 'future', 'harder'], 5: ['battle', 'hit', 'alot', 'boss', 'dark', 'hand', 'body', 'head', 'zone', 'city']}, {1: ['friend', 'problem', 'thing', 'story', 'reason', 'character', 'kind', 'minute', 'fact', 'type'], 2: ['game', 'time', 'people', 'world', 'way', 'play', 'support', 'point', 'fight', 'fix'], 3: ['hour', 'fun', 'experience', 'setting', 'day', 'session', 'month', 'money', 'week', 'work'], 4: ['battle', 'alot', 'boss', 'dark', 'window', 'cut', 'field', 'hand', 'middle', 'body'], 5: ['place', 'second', 'plenty', 'half', 'music', 'food', 'key', 'suck', 'move', 'worth']}, {1: ['friend', 'thing', 'problem', 'story', 'character', 'reason', 'minute', 'kind', 'type', 'fact'], 2: ['game', 'time', 'people', 'world', 'way', 'play', 'support', 'fight', 'point', 'feel'], 3: ['hour', 'fun', 'experience', 'setting', 'day', 'session', 'month', 'money', 'work', 'week'], 4: ['battle', 'cut', 'boss', 'dark', 'window', 'hand', 'head', 'field', 'lock', 'middle'], 5: ['plenty', 'suck', 'food', 'future', 'worth', 'sure', 'build', 'bunch', 'id', 'kill']}]
ldag7_game_7 = [{1: ['friend', 'problem', 'thing', 'story', 'kind', 'minute', 'reason', 'character', 'type', 'person'], 2: ['game', 'time', 'world', 'way', 'year', 'play', 'point', 'fight', 'end', 'feel'], 3: ['hour', 'experience', 'fun', 'setting', 'month', 'day', 'session', 'week', 'work', 'grind'], 4: ['food', 'breaking', 'music', 'future', 'jump', 'opening', 'speaking', 'country', 'fighting', 'kick'], 5: ['battle', 'boss', 'dark', 'hand', 'body', 'head', 'zone', 'cut', 'face', 'lock'], 6: ['support', 'fix', 'money', 'drop', 'hope', 'love', 'wait', 'deal', 'save', 'thanks'], 7: ['people', 'quality', 'lot', 'stuff', 'alot', 'random', 'mean', 'set', 'worth', 'plenty']}, {1: ['friend', 'problem', 'thing', 'story', 'reason', 'character', 'kind', 'minute', 'fact', 'type'], 2: ['game', 'time', 'people', 'world', 'way', 'play', 'point', 'fight', 'year', 'end'], 3: ['hour', 'fun', 'experience', 'setting', 'day', 'session', 'month', 'week', 'work', 'quality'], 4: ['boss', 'dark', 'cut', 'field', 'hand', 'middle', 'body', 'head', 'lock', 'shot'], 5: ['plenty', 'food', 'worth', 'post', 'bunch', 'breaking', 'kill', 'selling', 'speaking', 'writing'], 6: ['review', 'connection', 'mouse', 'steam', 'mission', 'launch', 'crash', 'map', 'network', 'dragon'], 7: ['support', 'fix', 'money', 'drop', 'wait', 'hope', 'deal', 'love', 'save', 'help']}, {1: ['friend', 'thing', 'problem', 'story', 'character', 'reason', 'minute', 'kind', 'type', 'fact'], 2: ['game', 'time', 'people', 'world', 'way', 'play', 'support', 'fight', 'point', 'feel'], 3: ['hour', 'fun', 'experience', 'setting', 'day', 'session', 'month', 'money', 'work', 'week'], 4: ['cut', 'boss', 'dark', 'hand', 'head', 'field', 'lock', 'middle', 'switch', 'zone'], 5: ['plenty', 'food', 'worth', 'bunch', 'post', 'stop', 'selling', 'track', 'breaking', 'fighting'], 6: ['review', 'connection', 'mouse', 'steam', 'mission', 'launch', 'crash', 'map', 'dragon', 'network'], 7: ['alot', 'hope', 'guess', 'damn', 'thats', 'lol', 'mean', 'hate', 'heard', 'thought']}]


# LIST LDA-GLOVE 500/1000/1500

ldag_edukasi_5 = [{1: ['design', 'project', 'information', 'concept', 'content', 'data', 'resume', 'experience', 'level', 'process'], 2: ['introduction', 'example', 'character', 'knowledge', 'explanation', 'background', 'artist', 'basic', 'principle', 'discussion'], 3: ['time', 'week', 'tool', 'class', 'work', 'job', 'exercise', 'field', 'step', 'sheet'], 4: ['game', 'theory', 'video', 'material', 'way', 'thing', 'idea', 'problem', 'topic', 'people'], 5: ['course', 'assignment', 'lecture', 'student', 'instructor', 'question', 'thanks', 'teacher', 'balance', 'application']}, {1: ['design', 'unity', 'project', 'concept', 'experience', 'beginner', 'level', 'skill', 'feedback', 'aspect'], 2: ['example', 'basic', 'knowledge', 'character', 'explanation', 'background', 'principle', 'approach', 'artist', 'opinion'], 3: ['game', 'thing', 'video', 'theory', 'way', 'material', 'idea', 'people', 'topic', 'question'], 4: ['course', 'time', 'week', 'lecture', 'thanks', 'class', 'work', 'student', 'teacher', 'professor'], 5: ['assignment', 'development', 'introduction', 'information', 'content', 'tool', 'process', 'data', 'document', 'instruction']}, {1: ['design', 'unity', 'project', 'concept', 'experience', 'beginner', 'web', 'level', 'skill', 'aspect'], 2: ['knowledge', 'example', 'basic', 'explanation', 'character', 'designer', 'understanding', 'quality', 'background', 'principle'], 3: ['course', 'time', 'week', 'lecture', 'thanks', 'teacher', 'class', 'work', 'student', 'fun'], 4: ['game', 'thing', 'video', 'material', 'way', 'theory', 'topic', 'idea', 'quiz', 'people'], 5: ['development', 'assignment', 'introduction', 'content', 'information', 'tool', 'process', 'data', 'instruction', 'peer']}]
ldag_edukasi_7 = [{1: ['project', 'experience', 'level', 'forum', 'skill', 'feedback', 'learning', 'insight', 'warehouse', 'addition'], 2: ['example', 'knowledge', 'explanation', 'artist', 'basic', 'principle', 'approach', 'opinion', 'quality', 'understanding'], 3: ['time', 'week', 'class', 'work', 'job', 'field', 'step', 'business', 'fun', 'practice'], 4: ['game', 'video', 'material', 'way', 'thing', 'idea', 'problem', 'topic', 'people', 'end'], 5: ['course', 'assignment', 'lecture', 'student', 'instructor', 'question', 'thanks', 'teacher', 'presentation', 'exam'], 6: ['information', 'content', 'tool', 'data', 'resume', 'process', 'exercise', 'discussion', 'analysis', 'balance'], 7: ['design', 'theory', 'introduction', 'concept', 'character', 'background', 'review', 'designer', 'sheet', 'instruction']}, {1: ['design', 'unity', 'project', 'concept', 'experience', 'beginner', 'level', 'skill', 'feedback', 'aspect'], 2: ['example', 'basic', 'knowledge', 'character', 'explanation', 'background', 'principle', 'approach', 'artist', 'opinion'], 3: ['thing', 'theory', 'material', 'idea', 'topic', 'problem', 'hand', 'answer', 'kind', 'stuff'], 4: ['week', 'class', 'work', 'job', 'fun', 'lesson', 'practice', 'start', 'day', 'help'], 5: ['development', 'introduction', 'information', 'content', 'tool', 'process', 'data', 'document', 'instruction', 'peer'], 6: ['game', 'time', 'video', 'way', 'people', 'step', 'lot', 'end', 'point', 'field'], 7: ['course', 'assignment', 'lecture', 'instructor', 'thanks', 'student', 'quiz', 'question', 'teacher', 'professor']}, {1: ['unity', 'project', 'experience', 'beginner', 'web', 'level', 'skill', 'aspect', 'developer', 'learning'], 2: ['knowledge', 'example', 'basic', 'explanation', 'understanding', 'quality', 'principle', 'approach', 'effort', 'artist'], 3: ['course', 'week', 'lecture', 'thanks', 'teacher', 'class', 'work', 'student', 'fun', 'professor'], 4: ['thing', 'material', 'topic', 'idea', 'quiz', 'question', 'hand', 'problem', 'stuff', 'kind'], 5: ['development', 'content', 'information', 'tool', 'process', 'data', 'peer', 'exercise', 'resume', 'engine'], 6: ['design', 'assignment', 'introduction', 'concept', 'theory', 'javascript', 'intro', 'instruction', 'html', 'review'], 7: ['game', 'time', 'video', 'way', 'people', 'step', 'end', 'lot', 'point', 'field']}]
ldag_ecommerce_5 = [{1: ['length', 'waist', 'medium', 'hip', 'shape', 'bust', 'pocket', 'room', 'tie', 'pound'], 2: ['material', 'person', 'piece', 'weight', 'compliment', 'review', 'thing', 'winter', 'issue', 'season'], 3: ['size', 'dress', 'fit', 'shirt', 'skirt', 'style', 'store', 'jacket', 'look', 'design'], 4: ['quality', 'way', 'time', 'love', 'summer', 'bit', 'work', 'online', 'day', 'feel'], 5: ['color', 'sleeve', 'cut', 'shoulder', 'pattern', 'lace', 'body', 'chest', 'arm', 'coat']}, {1: ['pant', 'length', 'waist', 'sleeve', 'medium', 'arm', 'shoulder', 'hip', 'lb', 'shape'], 2: ['person', 'piece', 'compliment', 'thing', 'winter', 'button', 'problem', 'reference', 'figure', 'kind'], 3: ['way', 'love', 'time', 'bit', 'fall', 'day', 'work', 'feel', 'summer', 'area'], 4: ['size', 'dress', 'color', 'fit', 'shirt', 'skirt', 'jean', 'style', 'jacket', 'model'], 5: ['sweater', 'material', 'quality', 'store', 'design', 'review', 'price', 'online', 'pattern', 'order']}, {1: ['size', 'dress', 'color', 'fabric', 'fit', 'skirt', 'quality', 'pant', 'medium', 'model'], 2: ['length', 'waist', 'sleeve', 'arm', 'jacket', 'body', 'shoulder', 'chest', 'bra', 'blue'], 3: ['sweater', 'material', 'style', 'person', 'picture', 'cute', 'compliment', 'thing', 'winter', 'problem'], 4: ['shirt', 'store', 'x', 'sale', 'review', 'cut', 'hip', 'online', 'photo', 'print'], 5: ['way', 'look', 'love', 'summer', 'time', 'day', 'bit', 'fall', 'work', 'feel']}]
ldag_ecommerce_7 = [{1: ['length', 'waist', 'medium', 'shape', 'bust', 'pocket', 'room', 'tie', 'pound', 'cotton'], 2: ['person', 'piece', 'compliment', 'thing', 'winter', 'season', 'problem', 'figure', 'opinion', 'type'], 3: ['size', 'dress', 'fit', 'shirt', 'skirt', 'style', 'jacket', 'look', 'jean', 'model'], 4: ['way', 'time', 'summer', 'bit', 'work', 'day', 'feel', 'spring', 'fall', 'year'], 5: ['color', 'sleeve', 'cut', 'shoulder', 'pattern', 'lace', 'body', 'chest', 'arm', 'coat'], 6: ['quality', 'material', 'store', 'design', 'sweater', 'online', 'weight', 'review', 'price', 'order'], 7: ['love', 'x', 'hip', 'dot', 'baby', 'dd', 'b', 'cream', 'hang', 'girl']}, {1: ['length', 'waist', 'medium', 'lb', 'shape', 'bust', 'room', 'pocket', 'leg', 'woman'], 2: ['person', 'piece', 'compliment', 'thing', 'winter', 'problem', 'reference', 'figure', 'kind', 'season'], 3: ['way', 'time', 'bit', 'fall', 'day', 'work', 'feel', 'summer', 'area', 'year'], 4: ['size', 'dress', 'fit', 'shirt', 'skirt', 'jean', 'style', 'jacket', 'model', 'look'], 5: ['sweater', 'material', 'quality', 'store', 'design', 'review', 'price', 'online', 'order', 'weight'], 6: ['color', 'pant', 'sleeve', 'coat', 'arm', 'shoulder', 'cut', 'pattern', 'lace', 'body'], 7: ['love', 'x', 'hip', 'cream', 'dot', 'girl', 'baby', 'c', 'saw', 'b']}, {1: ['fit', 'quality', 'design', 'price', 'shape', 'weight', 'purchase', 'issue', 'detail', 'brand'], 2: ['length', 'waist', 'arm', 'body', 'shoulder', 'chest', 'neck', 'knee', 'leg', 'stretch'], 3: ['material', 'person', 'compliment', 'thing', 'problem', 'figure', 'kind', 'reference', 'weather', 'type'], 4: ['store', 'x', 'sale', 'review', 'cut', 'hip', 'online', 'order', 'lb', 'button'], 5: ['way', 'love', 'summer', 'time', 'day', 'bit', 'fall', 'work', 'feel', 'area'], 6: ['look', 'picture', 'cute', 'photo', 'bra', 'top', 'tee', 'suit', 'wear', 'comfy'], 7: ['size', 'dress', 'color', 'fabric', 'shirt', 'sweater', 'skirt', 'pant', 'jean', 'style']}]
ldag_game_5 = [{1: ['monster', 'issue', 'friend', 'weapon', 'problem', 'thing', 'mouse', 'connection', 'version', 'series'], 2: ['game', 'time', 'hunter', 'people', 'world', 'way', 'control', 'support', 'fix', 'year'], 3: ['hour', 'review', 'server', 'graphic', 'experience', 'fun', 'setting', 'month', 'steam', 'day'], 4: ['hunt', 'release', 'content', 'menu', 'update', 'animation', 'campaign', 'addition', 'food', 'variety'], 5: ['player', 'keyboard', 'patch', 'title', 'enemy', 'core', 'dragon', 'screen', 'camera', 'movement']}, {1: ['monster', 'issue', 'friend', 'weapon', 'problem', 'thing', 'connection', 'mouse', 'story', 'series'], 2: ['game', 'time', 'hunter', 'people', 'world', 'way', 'control', 'p', 'play', 'support'], 3: ['hour', 'review', 'server', 'fun', 'experience', 'graphic', 'setting', 'day', 'steam', 'mission'], 4: ['player', 'port', 'controller', 'keyboard', 'patch', 'armor', 'title', 'core', 'enemy', 'frame'], 5: ['hunt', 'content', 'release', 'menu', 'update', 'animation', 'team', 'campaign', 'gathering', 'chat']}, {1: ['monster', 'issue', 'friend', 'weapon', 'thing', 'problem', 'connection', 'story', 'mouse', 'series'], 2: ['game', 'hunter', 'time', 'people', 'world', 'way', 'control', 'p', 'play', 'support'], 3: ['pc', 'hour', 'review', 'fun', 'server', 'graphic', 'experience', 'setting', 'day', 'steam'], 4: ['player', 'port', 'controller', 'keyboard', 'patch', 'armor', 'title', 'frame', 'dragon', 'core'], 5: ['hunt', 'content', 'release', 'menu', 'update', 'variety', 'animation', 'addition', 'gathering', 'hunting']}, ]
ldag_game_7 = [{1: ['monster', 'issue', 'friend', 'weapon', 'problem', 'thing', 'mouse', 'connection', 'version', 'series'], 2: ['game', 'time', 'hunter', 'world', 'way', 'control', 'year', 'play', 'point', 'fight'], 3: ['hour', 'review', 'server', 'graphic', 'experience', 'fun', 'setting', 'month', 'steam', 'day'], 4: ['hunt', 'content', 'menu', 'animation', 'campaign', 'addition', 'food', 'variety', 'potato', 'farm'], 5: ['player', 'keyboard', 'patch', 'title', 'enemy', 'core', 'dragon', 'screen', 'camera', 'movement'], 6: ['support', 'release', 'fix', 'money', 'update', 'drop', 'hope', 'love', 'edit', 'wait'], 7: ['people', 'quality', 'couple', 'lot', 'skill', 'stuff', 'date', 'god', 'matter', 'alot']}, {1: ['issue', 'friend', 'problem', 'thing', 'story', 'performance', 'option', 'reason', 'character', 'kind'], 2: ['game', 'time', 'people', 'world', 'way', 'control', 'p', 'play', 'point', 'fight'], 3: ['hour', 'fun', 'experience', 'setting', 'day', 'session', 'month', 'week', 'work', 'quality'], 4: ['player', 'title', 'enemy', 'frame', 'movement', 'bow', 'boss', 'dark', 'bone', 'portion'], 5: ['content', 'menu', 'campaign', 'addition', 'plenty', 'food', 'potato', 'variety', 'worth', 'post'], 6: ['monster', 'hunter', 'pc', 'multiplayer', 'review', 'weapon', 'port', 'connection', 'mouse', 'server'], 7: ['support', 'fix', 'money', 'drop', 'wait', 'gt', 'edit', 'hope', 'input', 'limit']}, {1: ['issue', 'friend', 'thing', 'problem', 'story', 'option', 'performance', 'character', 'fan', 'reason'], 2: ['game', 'time', 'people', 'world', 'way', 'control', 'p', 'play', 'support', 'fight'], 3: ['hour', 'fun', 'experience', 'setting', 'day', 'session', 'month', 'money', 'work', 'week'], 4: ['player', 'title', 'frame', 'enemy', 'movement', 'bow', 'cut', 'boss', 'dark', 'bar'], 5: ['content', 'menu', 'variety', 'addition', 'plenty', 'chat', 'campaign', 'crafting', 'food', 'potato'], 6: ['monster', 'hunter', 'pc', 'weapon', 'multiplayer', 'review', 'port', 'connection', 'server', 'gameplay'], 7: ['alot', 'hope', 'damage', 'gathering', 'guess', 'damn', 'resource', 'thats', 'move', 'ability']}]


#   LIST LDA SORT LDA 1000

#   LIST LDA SORT LDA-TFIDF 1000
# LIST BTM 1000
#   LIST LDA-GLOVE 0,7 1000
# LIST LDA-GLOVE 1000

#   LIST LDA SORT LDA 1500
#   LIST LDA SORT LDA-TFIDF 1500
# LIST BTM 1500
#   LIST LDA-GLOVE 0,7 1500
# LIST LDA-GLOVE 1500

